// Generated by sprotodump. DO NOT EDIT!
// source: ../protocol/game.sproto

using System;
using Sproto;
using System.Collections.Generic;

namespace SprotoType { 
	public class charData : SprotoTypeBase {
		private static int max_field_count = 5;
		
		
		private string _id; // tag 0
		public string id {
			get { return _id; }
			set { base.has_field.set_field (0, true); _id = value; }
		}
		public bool HasId {
			get { return base.has_field.has_field (0); }
		}

		private Int64 _elite; // tag 1
		public Int64 elite {
			get { return _elite; }
			set { base.has_field.set_field (1, true); _elite = value; }
		}
		public bool HasElite {
			get { return base.has_field.has_field (1); }
		}

		private Int64 _level; // tag 2
		public Int64 level {
			get { return _level; }
			set { base.has_field.set_field (2, true); _level = value; }
		}
		public bool HasLevel {
			get { return base.has_field.has_field (2); }
		}

		private Int64 _exp; // tag 3
		public Int64 exp {
			get { return _exp; }
			set { base.has_field.set_field (3, true); _exp = value; }
		}
		public bool HasExp {
			get { return base.has_field.has_field (3); }
		}

		private Int64 _trust; // tag 4
		public Int64 trust {
			get { return _trust; }
			set { base.has_field.set_field (4, true); _trust = value; }
		}
		public bool HasTrust {
			get { return base.has_field.has_field (4); }
		}

		public charData () : base(max_field_count) {}

		public charData (byte[] buffer) : base(max_field_count, buffer) {
			this.decode ();
		}

		protected override void decode () {
			int tag = -1;
			while (-1 != (tag = base.deserialize.read_tag ())) {
				switch (tag) {
				case 0:
					this.id = base.deserialize.read_string ();
					break;
				case 1:
					this.elite = base.deserialize.read_integer ();
					break;
				case 2:
					this.level = base.deserialize.read_integer ();
					break;
				case 3:
					this.exp = base.deserialize.read_integer ();
					break;
				case 4:
					this.trust = base.deserialize.read_integer ();
					break;
				default:
					base.deserialize.read_unknow_data ();
					break;
				}
			}
		}

		public override int encode (SprotoStream stream) {
			base.serialize.open (stream);

			if (base.has_field.has_field (0)) {
				base.serialize.write_string (this.id, 0);
			}

			if (base.has_field.has_field (1)) {
				base.serialize.write_integer (this.elite, 1);
			}

			if (base.has_field.has_field (2)) {
				base.serialize.write_integer (this.level, 2);
			}

			if (base.has_field.has_field (3)) {
				base.serialize.write_integer (this.exp, 3);
			}

			if (base.has_field.has_field (4)) {
				base.serialize.write_integer (this.trust, 4);
			}

			return base.serialize.close ();
		}
	}


	public class getPlayerData {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 2;
			
			
			private Int64 _uid; // tag 0
			public Int64 uid {
				get { return _uid; }
				set { base.has_field.set_field (0, true); _uid = value; }
			}
			public bool HasUid {
				get { return base.has_field.has_field (0); }
			}

			private Int64 _version; // tag 1
			public Int64 version {
				get { return _version; }
				set { base.has_field.set_field (1, true); _version = value; }
			}
			public bool HasVersion {
				get { return base.has_field.has_field (1); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.uid = base.deserialize.read_integer ();
						break;
					case 1:
						this.version = base.deserialize.read_integer ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.uid, 0);
				}

				if (base.has_field.has_field (1)) {
					base.serialize.write_integer (this.version, 1);
				}

				return base.serialize.close ();
			}
		}


		public class response : SprotoTypeBase {
			private static int max_field_count = 10;
			
			
			private Int64 _result; // tag 0
			public Int64 result {
				get { return _result; }
				set { base.has_field.set_field (0, true); _result = value; }
			}
			public bool HasResult {
				get { return base.has_field.has_field (0); }
			}

			private Int64 _version; // tag 1
			public Int64 version {
				get { return _version; }
				set { base.has_field.set_field (1, true); _version = value; }
			}
			public bool HasVersion {
				get { return base.has_field.has_field (1); }
			}

			private Int64 _level; // tag 2
			public Int64 level {
				get { return _level; }
				set { base.has_field.set_field (2, true); _level = value; }
			}
			public bool HasLevel {
				get { return base.has_field.has_field (2); }
			}

			private Int64 _exp; // tag 3
			public Int64 exp {
				get { return _exp; }
				set { base.has_field.set_field (3, true); _exp = value; }
			}
			public bool HasExp {
				get { return base.has_field.has_field (3); }
			}

			private Int64 _reason; // tag 4
			public Int64 reason {
				get { return _reason; }
				set { base.has_field.set_field (4, true); _reason = value; }
			}
			public bool HasReason {
				get { return base.has_field.has_field (4); }
			}

			private List<charData> _charList; // tag 5
			public List<charData> charList {
				get { return _charList; }
				set { base.has_field.set_field (5, true); _charList = value; }
			}
			public bool HasCharList {
				get { return base.has_field.has_field (5); }
			}

			private List<string> _squad; // tag 6
			public List<string> squad {
				get { return _squad; }
				set { base.has_field.set_field (6, true); _squad = value; }
			}
			public bool HasSquad {
				get { return base.has_field.has_field (6); }
			}

			private string _desktopChar; // tag 7
			public string desktopChar {
				get { return _desktopChar; }
				set { base.has_field.set_field (7, true); _desktopChar = value; }
			}
			public bool HasDesktopChar {
				get { return base.has_field.has_field (7); }
			}

			private List<itemStack> _items; // tag 8
			public List<itemStack> items {
				get { return _items; }
				set { base.has_field.set_field (8, true); _items = value; }
			}
			public bool HasItems {
				get { return base.has_field.has_field (8); }
			}

			private List<string> _permissions; // tag 9
			public List<string> permissions {
				get { return _permissions; }
				set { base.has_field.set_field (9, true); _permissions = value; }
			}
			public bool HasPermissions {
				get { return base.has_field.has_field (9); }
			}

			public response () : base(max_field_count) {}

			public response (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.result = base.deserialize.read_integer ();
						break;
					case 1:
						this.version = base.deserialize.read_integer ();
						break;
					case 2:
						this.level = base.deserialize.read_integer ();
						break;
					case 3:
						this.exp = base.deserialize.read_integer ();
						break;
					case 4:
						this.reason = base.deserialize.read_integer ();
						break;
					case 5:
						this.charList = base.deserialize.read_obj_list<charData> ();
						break;
					case 6:
						this.squad = base.deserialize.read_string_list ();
						break;
					case 7:
						this.desktopChar = base.deserialize.read_string ();
						break;
					case 8:
						this.items = base.deserialize.read_obj_list<itemStack> ();
						break;
					case 9:
						this.permissions = base.deserialize.read_string_list ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.result, 0);
				}

				if (base.has_field.has_field (1)) {
					base.serialize.write_integer (this.version, 1);
				}

				if (base.has_field.has_field (2)) {
					base.serialize.write_integer (this.level, 2);
				}

				if (base.has_field.has_field (3)) {
					base.serialize.write_integer (this.exp, 3);
				}

				if (base.has_field.has_field (4)) {
					base.serialize.write_integer (this.reason, 4);
				}

				if (base.has_field.has_field (5)) {
					base.serialize.write_obj (this.charList, 5);
				}

				if (base.has_field.has_field (6)) {
					base.serialize.write_string (this.squad, 6);
				}

				if (base.has_field.has_field (7)) {
					base.serialize.write_string (this.desktopChar, 7);
				}

				if (base.has_field.has_field (8)) {
					base.serialize.write_obj (this.items, 8);
				}

				if (base.has_field.has_field (9)) {
					base.serialize.write_string (this.permissions, 9);
				}

				return base.serialize.close ();
			}
		}


	}


	public class handshake {
	
		public class response : SprotoTypeBase {
			private static int max_field_count = 3;
			
			
			private Int64 _result; // tag 0
			public Int64 result {
				get { return _result; }
				set { base.has_field.set_field (0, true); _result = value; }
			}
			public bool HasResult {
				get { return base.has_field.has_field (0); }
			}

			private Int64 _uid; // tag 1
			public Int64 uid {
				get { return _uid; }
				set { base.has_field.set_field (1, true); _uid = value; }
			}
			public bool HasUid {
				get { return base.has_field.has_field (1); }
			}

			private Int64 _dataVersion; // tag 2
			public Int64 dataVersion {
				get { return _dataVersion; }
				set { base.has_field.set_field (2, true); _dataVersion = value; }
			}
			public bool HasDataVersion {
				get { return base.has_field.has_field (2); }
			}

			public response () : base(max_field_count) {}

			public response (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.result = base.deserialize.read_integer ();
						break;
					case 1:
						this.uid = base.deserialize.read_integer ();
						break;
					case 2:
						this.dataVersion = base.deserialize.read_integer ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.result, 0);
				}

				if (base.has_field.has_field (1)) {
					base.serialize.write_integer (this.uid, 1);
				}

				if (base.has_field.has_field (2)) {
					base.serialize.write_integer (this.dataVersion, 2);
				}

				return base.serialize.close ();
			}
		}


	}


	public class heartbeat {
	
		public class response : SprotoTypeBase {
			private static int max_field_count = 1;
			
			
			private Int64 _result; // tag 0
			public Int64 result {
				get { return _result; }
				set { base.has_field.set_field (0, true); _result = value; }
			}
			public bool HasResult {
				get { return base.has_field.has_field (0); }
			}

			public response () : base(max_field_count) {}

			public response (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.result = base.deserialize.read_integer ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.result, 0);
				}

				return base.serialize.close ();
			}
		}


	}


	public class itemStack : SprotoTypeBase {
		private static int max_field_count = 2;
		
		
		private Int64 _id; // tag 0
		public Int64 id {
			get { return _id; }
			set { base.has_field.set_field (0, true); _id = value; }
		}
		public bool HasId {
			get { return base.has_field.has_field (0); }
		}

		private Int64 _amount; // tag 1
		public Int64 amount {
			get { return _amount; }
			set { base.has_field.set_field (1, true); _amount = value; }
		}
		public bool HasAmount {
			get { return base.has_field.has_field (1); }
		}

		public itemStack () : base(max_field_count) {}

		public itemStack (byte[] buffer) : base(max_field_count, buffer) {
			this.decode ();
		}

		protected override void decode () {
			int tag = -1;
			while (-1 != (tag = base.deserialize.read_tag ())) {
				switch (tag) {
				case 0:
					this.id = base.deserialize.read_integer ();
					break;
				case 1:
					this.amount = base.deserialize.read_integer ();
					break;
				default:
					base.deserialize.read_unknow_data ();
					break;
				}
			}
		}

		public override int encode (SprotoStream stream) {
			base.serialize.open (stream);

			if (base.has_field.has_field (0)) {
				base.serialize.write_integer (this.id, 0);
			}

			if (base.has_field.has_field (1)) {
				base.serialize.write_integer (this.amount, 1);
			}

			return base.serialize.close ();
		}
	}


	public class package : SprotoTypeBase {
		private static int max_field_count = 3;
		
		
		private Int64 _type; // tag 0
		public Int64 type {
			get { return _type; }
			set { base.has_field.set_field (0, true); _type = value; }
		}
		public bool HasType {
			get { return base.has_field.has_field (0); }
		}

		private Int64 _session; // tag 1
		public Int64 session {
			get { return _session; }
			set { base.has_field.set_field (1, true); _session = value; }
		}
		public bool HasSession {
			get { return base.has_field.has_field (1); }
		}

		private string _ud; // tag 2
		public string ud {
			get { return _ud; }
			set { base.has_field.set_field (2, true); _ud = value; }
		}
		public bool HasUd {
			get { return base.has_field.has_field (2); }
		}

		public package () : base(max_field_count) {}

		public package (byte[] buffer) : base(max_field_count, buffer) {
			this.decode ();
		}

		protected override void decode () {
			int tag = -1;
			while (-1 != (tag = base.deserialize.read_tag ())) {
				switch (tag) {
				case 0:
					this.type = base.deserialize.read_integer ();
					break;
				case 1:
					this.session = base.deserialize.read_integer ();
					break;
				case 2:
					this.ud = base.deserialize.read_string ();
					break;
				default:
					base.deserialize.read_unknow_data ();
					break;
				}
			}
		}

		public override int encode (SprotoStream stream) {
			base.serialize.open (stream);

			if (base.has_field.has_field (0)) {
				base.serialize.write_integer (this.type, 0);
			}

			if (base.has_field.has_field (1)) {
				base.serialize.write_integer (this.session, 1);
			}

			if (base.has_field.has_field (2)) {
				base.serialize.write_string (this.ud, 2);
			}

			return base.serialize.close ();
		}
	}


}


public class Protocol : ProtocolBase {
	public static  Protocol Instance = new Protocol();
	private Protocol() {
		Protocol.SetProtocol<getPlayerData> (getPlayerData.Tag);
		Protocol.SetRequest<SprotoType.getPlayerData.request> (getPlayerData.Tag);
		Protocol.SetResponse<SprotoType.getPlayerData.response> (getPlayerData.Tag);

		Protocol.SetProtocol<handshake> (handshake.Tag);
		Protocol.SetResponse<SprotoType.handshake.response> (handshake.Tag);

		Protocol.SetProtocol<heartbeat> (heartbeat.Tag);
		Protocol.SetResponse<SprotoType.heartbeat.response> (heartbeat.Tag);

		Protocol.SetProtocol<register> (register.Tag);

	}

	public class getPlayerData {
		public const int Tag = 4;
	}

	public class handshake {
		public const int Tag = 1;
	}

	public class heartbeat {
		public const int Tag = 2;
	}

	public class register {
		public const int Tag = 3;
	}

}